[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
# Production-specific configuration
[environments.production.variables]
DEBUG = "false"
LOG_LEVEL = "INFO"
API_TITLE = "Resume Screening API"
API_VERSION = "1.0.0"
API_DESCRIPTION = "FastAPI application for resume screening using LlamaExtract"

# File upload settings
MAX_FILE_SIZE = "10485760"  # 10MB
UPLOAD_DIR = "uploads"

# Rate limiting
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "3600"

# Background tasks
MAX_BACKGROUND_TASKS = "10"
TASK_TIMEOUT = "600"

# Security
ACCESS_TOKEN_EXPIRE_MINUTES = "30"

# CORS settings for production
CORS_ALLOW_CREDENTIALS = "false"

# LlamaExtract settings
LLAMA_EXTRACT_AGENT_NAME = "resume-screening-api"
LLAMA_EXTRACT_TIMEOUT = "300"

# Database settings (will use Railway PostgreSQL addon)
USE_IN_MEMORY_DB = "false"

# DigitalOcean Spaces (optional)
USE_SPACES = "false"
SPACES_ACL = "public-read"
SPACES_DELETE_LOCAL_AFTER_UPLOAD = "false"

[environments.staging]
# Staging environment configuration
[environments.staging.variables]
DEBUG = "true"
LOG_LEVEL = "DEBUG"
API_TITLE = "Resume Screening API (Staging)"
API_VERSION = "1.0.0-staging"

# File upload settings
MAX_FILE_SIZE = "10485760"
UPLOAD_DIR = "uploads"

# Rate limiting (more permissive for testing)
RATE_LIMIT_REQUESTS = "200"
RATE_LIMIT_WINDOW = "3600"

# Background tasks
MAX_BACKGROUND_TASKS = "5"
TASK_TIMEOUT = "300"

# Security
ACCESS_TOKEN_EXPIRE_MINUTES = "60"

# CORS settings for staging (more permissive)
CORS_ALLOW_CREDENTIALS = "false"

# LlamaExtract settings
LLAMA_EXTRACT_AGENT_NAME = "resume-screening-staging"
LLAMA_EXTRACT_TIMEOUT = "300"

# Database settings
USE_IN_MEMORY_DB = "false"

# DigitalOcean Spaces (optional)
USE_SPACES = "false"

# Development-friendly settings
[environments.development]
[environments.development.variables]
DEBUG = "true"
LOG_LEVEL = "DEBUG"
API_TITLE = "Resume Screening API (Development)"
API_VERSION = "1.0.0-dev"

# More permissive settings for development
MAX_FILE_SIZE = "20971520"  # 20MB for dev
RATE_LIMIT_REQUESTS = "1000"
RATE_LIMIT_WINDOW = "3600"

# Shorter timeouts for faster iteration
TASK_TIMEOUT = "180"
ACCESS_TOKEN_EXPIRE_MINUTES = "120"

# CORS settings for development
CORS_ALLOW_CREDENTIALS = "true"

# LlamaExtract settings
LLAMA_EXTRACT_AGENT_NAME = "resume-screening-dev"
LLAMA_EXTRACT_TIMEOUT = "180"

# Use in-memory DB for development if needed
USE_IN_MEMORY_DB = "true"

# DigitalOcean Spaces disabled for dev
USE_SPACES = "false"
